#!/bin/bash
#
# Michael Piko
# backup up pi to my LTSP server. 
# 9-62014
# last modified: 

#see setEnvironment.sh, functions.sh, and variables.sh for explaination
. setEnvironment.sh

buildpath $LOGDIR
cleandir $LOGDIR 2
recordscriptrun $(basename $0) $LOGBASE

SOURCE=/home/pi/
DEST=/home/backup/pi/occidentalis
REMOTE=pi@192.168.1.28

ssh $REMOTE "[ -d $DEST ] && mkdir -p $DEST"

if [ $# -eq 1 ] && [ $1 = "-v" ]
then
  rsync -azPve ssh $SOURCE $REMOTE:$DEST --delete --partial --exclude '*~' --exclude log --exclude Downloads --exclude .local/share/Trash
else
  rsync -azve ssh $SOURCE $REMOTE:$DEST --delete --partial --exclude '*~' --exclude log --exclude Downloads --exclude .local/share/Trash > $LOGFILE
fi



