#!/bin/bash

alias vi=vim
alias ll='ls -l'
alias lr='ls -1tr'
alias reboot='sudo reboot'
alias shutdown='sudo shutdown -h now'
alias halt='sudo halt -p'
alias dd='dd status=progress'
alias psg='ps ax | grep -v grep | grep'
alias wget='wget -c'
alias ..='cd ..'
alias ...='cd ../..'
#alias youtube-dl='youtube-dl --recode-video mp4'
alias mount='sudo mount'
alias apt='sudo apt'
alias clamscan='clamscan -r'
alias lsnc='ls --color=never'
alias nano='vim'
alias tesseract='tesseract --psm 6'
alias rsync='rsync -C --exclude="__pycache__"'
alias pandoc='pandoc -V --lang=en_AU'
alias logdate='date "+%Y-%m-%d_%H:%M"'
alias tree='tree -v'
alias now='date "+%Y%m%d_%H%M"'
alias tstamp='date "+%Y%m%d_%H%M"'
