#!/bin/bash

SELF=$(basename $0)
PROD=8107811@berkeley-engineering.odoo.com
STAGING=8246887@berkeley-engineering-staging-8246887.dev.odoo.com

ENV=$PROD

for ARG in $@
do
    if [ $ARG = "-d" ]
    then
        ACTIONS="./deactivate_cyder"
    elif [ $ARG = "-a" ]
    then
        ACTIONS="./activate_cyder"
    elif [ $ARG = "-m" ]
    then
        ACTIONS="./activate_michael"
    elif [ $ARG = "-s" ]
    then
        ENV=$STAGING
    fi
done

if [ -z "$ACTIONS" ]
then
    ssh $ENV 
else
    ssh $ENV \"$ACTIONS\"
fi
