#!/bin/bash

BLOCKSIZE=512
MINSIZE=100000000


# how many blocks have been allocated so far?
BLOCKSALLOCATED=$(stat --printf=%b "$1")

# get the size of the file
SIZE_IN_BYTES=$(stat --printf=%s "$1")

# How many blocks will the completed file be?
TOTALBLOCKS=$(expr $SIZE_IN_BYTES \/ $BLOCKSIZE)

# work out what percentage we are up to
PERCENTILE=$(expr $BLOCKSALLOCATED \* 100 \/ $TOTALBLOCKS)


RAWTIME=$(date +"%s")

CHANGEDTIME=$(stat --printf=%Z "$1")

TIMEDELTA=$(expr $RAWTIME - $CHANGEDTIME)

if [ $TIMEDELTA -gt 59 ]
then 
  if [ $PERCENTILE -ge 100 ]
  then
    STATE="COMPLETE"
  else
    STATE="STALE"
  fi
elif [ $SIZE_IN_BYTES -lt $MINSIZE ]
then
   STATE="Too Small" 
else
  STATE="Downloading"
fi

echo "$STATE: $1 at ${PERCENTILE}%"
