#!/bin/bash

if [ $# -eq 1 ]
then
    OUT=$1
else
    OUT=out.xls
fi

if [ $(ls -1 *.csv 2> /dev/null | wc -l ) -ne 0 ]
then
    if which ssconvert > /dev/null
    then
        ssconvert *.csv --merge-to=$OUT
    else
        echo "no ssconvert on this machine"
    fi
else
    echo "No csv files found"
fi
