#!/bin/bash

SELF=$(basename $0)
. $HOME/.clients

PRODUCTION=$CYDER_PROD
STAGING=$CYDER_STAGING

if [ $# -gt 0 ]
then
    if [ $1 = "-s" ]
    then
        shift
        ssh $STAGING "$@"
    else
        ssh $PRODUCTION "$@"
    fi
else
    ssh $PRODUCTION
fi
