#!/bin/bash

SELF=$(basename $0)
PRODUCTION=4518917@cyder-solutions.odoo.com
STAGING=6546539@cyder-solutions-staging-6546539.dev.odoo.com

if [ $# -eq 1 ]
then
    if [ $1 = "-d" ]
    then
        ssh $PRODUCTION "./deactivate_employees"
    elif [ $1 = "-a" ]
    then
        ssh $PRODUCTION "./activate_employees"
    elif [ $1 = "-s" ]
    then
        ssh $STAGING
    else
        echo "dont know what to do with $1"
        echo "Usage: $SELF [-a|-d|-s]"
    fi
else
    ssh $PRODUCTION
fi
