#!/bin/bash

SELF=$(basename $0)
PRODUCTION=2887485@essential-caravans.odoo.com

if [ $# -eq 1 ]
then
    if [ $1 = "-d" ]
    then
        ssh $PRODUCTION "./deactivate_cyder"
    elif [ $1 = "-a" ]
    then
        ssh $PRODUCTION "./activate_cyder"
    elif [ $1 = "-m" ]
    then
        ssh $PRODUCTION "./activate_michael"
    else
        echo "dont know what to do with $1"
        echo "Usage: $SELF [-a|-d|-m]"
    fi
else
    ssh $PRODUCTION
fi
