#!/bin/bash

SELF=$(basename $0)
PROD=2887485@essential-caravans.odoo.com
STAGING=7646480@essential-caravans-stage-7646480.dev.odoo.com

ENV=$PROD

for ARG in $@
do
    if [ $ARG = "-d" ]
    then
        ACTIONS="./deactivate_cyder"
    elif [ $ARG = "-a" ]
    then
        ACTIONS="./activate_cyder"
    elif [ $ARG = "-m" ]
    then
        ACTIONS="./activate_michael"
    elif [ $ARG = "-s" ]
    then
        ENV=$STAGING
    fi
done

if [ -z "$ACTIONS" ]
then
    ssh $ENV 
else
    ssh $ENV \"$ACTIONS\"
fi
