#!/bin/bash

sudo apt install git -y

cd
git config --global user.name "mpiko"
git config --global user.email "michael@piko.com.au"
#git init
git clone https://github.com/mpiko/scripts bin
git clone https://github.com/mpiko/localbin localbin
