#!/bin/bash

INTERFACES=$(ifconfig | grep '^[a-zA-Z0-9]' | cut -f1 -d" " | sed 's/://g')

for i in $INTERFACES
do
    if [ $i == lo ]
    then
        continue
    fi
    IP=$(ifconfig $i | grep -w inet | gawk '{print $2}')
    echo "$i    $IP"
done

