#!/bin/bash

CURRENT=.current
if [ $# -gt 0 ]
then
    TOPIC="$@"
fi

while [ -z "$TOPIC" ]
do
    read -p "What is the new topic? " TOPIC
    [ -z "$TOPIC" ] && echo "No topic supplied" && exit 1
done

[ -d "$TOPIC" ] || mkdir "$TOPIC"

SUB=new
COUNT=0
while [ "$SUB" != "done" ]
do 
    if [ $COUNT -eq 0 ]
    then
        read -p "What is the next subtopic name (Default = 0. Introduction)? " SUB
        [ -z "$SUB" ] && SUB="Introduction"
    else
        read -p "What is the next subtopic name ($COUNT)? " SUB
        while [ -z "$SUB" ]
        do
            echo "No response. Please proved a topic"
            read -p "What is the next subtopic name ($COUNT)? " SUB
        done
    fi
    [ "$SUB" = "conc" ] && SUB=Conclusion
    [ "$SUB" = "end" ] && break
    [ -d "$TOPIC/${COUNT}. $SUB" ] || mkdir "$TOPIC/${COUNT}. $SUB"
    [ "$SUB" = "Conclusion" ] && break
    [ $COUNT -eq 0 ] && LINK="$TOPIC/${COUNT}. $SUB"
    (( COUNT++ ))
done

# will we create the link in dwhelper?
read -p "Would you like a link in dwhelper (Y/n)? " DW
[ -z "$DW" ] && DW='Y'
[ "$DW" = 'y' ] && DW='Y'
if [ $DW = 'Y' ]
then
    PWD=$(pwd)
    [ -L $HOME/dwhelper/$CURRENT ] && rm $HOME/dwhelper/$CURRENT
    LILink "$PWD/$LINK"
fi
    


