#!/bin/bash

COUNTTXT=.count.txt

if [ $# -eq 1 ]
then
    DIR=$1
else
    read -p "which directory would you like? " DIR
    [ -z $DIR ] && exit
fi

writeDurations() {
    /home/michael/bin/getMP4Duration "$DIR" > "$DIR/.durations.txt"
    mv "$DIR/.durations.txt" "$DIR/durations.txt"
}
PLINES=0
while [ -f /home/michael/dwhelper/$COUNTTXT ]
do
    LINES=$(find "$DIR" -type f -iname '*.mp4'| wc -l)
    #echo LINES: $LINES PLINES: $PLINES
    if [ $LINES -eq 0 ]
    then
        echo "00:00" > "$DIR/durations.txt"
    else
        [ $LINES -eq $PLINES ] && sleep 2 && continue

        writeDurations
        PLINES=$(find "$DIR" -type f | wc -l)
    fi
    sleep 30
done
writeDurations


