#!/bin/bash

# set up temp dir
#TMP=/tmp/michael
#[ -d $TMP ] || mkdir $TMP
[ -e /tmp/$USER ] || mkdir /tmp/$USER
[ -e $HOME/temp ] || ln -s /tmp/$USER $HOME/temp


if ! echo $PATH | grep $HOME/bin > /dev/null ; then
  PATH=$HOME/bin:$PATH
fi

if [ -d $HOME/localbin ]
then
  PATH=$PATH:$HOME/localbin
fi

if [ -d $HOME/.local/bin ]
then
  PATH=$PATH:$HOME/.local/bin
fi

if [ -d $HOME/devbin ]
then
  PATH=$PATH:$HOME/devbin
fi


export TMP PATH

function color_my_prompt {
    local __user_and_host="\[\033[01;32m\]\u@\h"
    local __cur_location="\[\033[01;34m\]\w"
    local __git_branch_color="\[\033[31m\]"
    local __git_branch='`git branch 2> /dev/null | grep -e ^* | sed -E  s/^\\\\\*\ \(.+\)$/\(\\\\\1\)\ /`'
    local __prompt_tail="\[\033[35m\]$"
    local __last_color="\[\033[00m\]"
    export PS1="$__user_and_host $__cur_location $__git_branch_color$__git_branch$__prompt_tail$__last_color "
}
color_my_prompt

case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

function mls() {
ls -lh $1 | gawk '{print $5," ",$9}'
}
export -f mls
