#!/bin/bash 

# TODO
# need to put some comments in here.



#-----------------------------------------------------------------
# Options. TODO need to add a switch on the command line.
# html headers should be off if output is for Odoo Knowledge
HTMLWRAPPER="OFF"   # OFF = just the body of the knowledge article.
                    # ON if you want to create a standalone web page.
CSV="ON"            # ready for import
CSVHEADERS="ON"     # turn off if adding to an existing file

#-----------------------------------------------------------------
if [ $CSV = "ON" ]
then
    read -p "what ID would you like to use? (default = know_book_0001) " ID
    [ -z "$ID" ] && ID="know_book_0001"
    read -p "What parent location? (default = Books) " PARENT
    [ -z "$PARENT" ] && PARENT="Books"
fi

#-----------------------------------------------------------------
IFS="
"

#-----------------------------------------------------------------
# check for input
if [ $# -ne 1 ]
then
    read -p "Which file? " INPUT
else
    INPUT=$1
fi

if [ ! -e "$1" ]
then
    echo "Cannot find \"$1\""
    exit 1
fi

#-----------------------------------------------------------------
# functions
togglePara() {
    if [ $PARA = "ON" ]
    then
        echo -n "</p> "
        PARA=OFF
    else
        echo -n "<p> "
        PARA=ON
    fi
}

bulletsOff() {
    if [ $BULLETS = "ON" ]
    then
        echo -n "</li></ul>"
        BULLETS="OFF"
    fi
}

display() {
    echo -n "$@" \
        | sed 's/ \+/ /g' \
        | sed 's/\"/\&quot;/g' \
        | sed 's#\*\*\([a-zA-Z0-9\.:"\\\(\\\)]\)#<b>\1#' \
        | sed 's#\([a-zA-Z0-9\.:"\\\(\\\)]\)\*\*#\1</b>#'
}

#-----------------------------------------------------------------
PARA=OFF
BULLETS=OFF
TITLE=$(echo $INPUT | sed 's/.md//g')

#-----------------------------------------------------------------
if [ "$CSV" = "ON" ]
then
    if [ $CSVHEADERS = "ON" ]
    then
        echo "\"id\",\"name\",parent_id\",\"body\""
    fi
    echo -n "\"$ID\",\"$TITLE\",\"$PARENT\",\""
fi
#-----------------------------------------------------------------
if [ $HTMLWRAPPER = "ON" ]
then
    display "<html><title>"
    display $TITLE
    display "</title><body>"
else
    display "<h1>"
    display $INPUT | sed 's/.md//g'
    display "</h1>"
fi

#-----------------------------------------------------------------
COUNTER=1
for LINE in $(cat $INPUT)
do
    #echo -n $COUNTER: 
    (( COUNTER++ ))
    TEXT=$(echo $LINE | sed 's/^ *//')
    HEADING=$(echo $TEXT | gawk '{print $1}')
    CHAR=$(echo $HEADING | cut -b1)
    CLEAN=$(echo $TEXT | sed 's/^#\+//')

    #[ $COUNTER = 3 ] && set -x || set +x
    if [ "$CHAR" = "#" ]
    then
        bulletsOff
        NUM=$(echo $HEADING | wc -c)
        (( NUM-- ))
        CLEAN=$(echo $CLEAN | sed 's/\*//g')
        display "<h$NUM>$CLEAN</h$NUM>"
    #-------------------------------------------------------------
    elif [ "$HEADING" = "---" ]
    then
        display "<hr/>"
    #-------------------------------------------------------------
    elif [ "$CHAR" = "-" ]
    then
        # TODO
        # we are in a bullet list.
        if [ $BULLETS = "OFF" ]
        then
            BULLETS="ON"
            echo -n "<ul><li>"
        else
            echo -n "<li>"
        fi
        display $(echo $CLEAN | sed 's/^- //')
    #-------------------------------------------------------------
    else
        bulletsOff
        togglePara
        display $CLEAN
    fi
    [ $PARA = "ON" ] && togglePara
done
bulletsOff
if [ $HTMLWRAPPER = "ON" ]
then
    display "</body></html>"
fi
if [ $CSV = "ON" ]
then
    echo "\""
else
    echo ""
fi
