#!/bin/bash

OUT="/home/michael/Obsidian/Tradies vault/Books/5 Essential Business Strategies for Tradespeople.md"

FILES="Introduction to Cyder Academy.md
Chapter 1 Effective Marketing.md
Chapter 2 Financial Management.md
Chapter 2.2 Financial Statements.md
Chapter 3 Customer Relationship Management (CRM).md
Chapter 3.1 The CRM Process - From Inquiry to Opportunity Won or Lost.md
Chapter 4 Business Growth.md
Chapter 5 Continual Learning and Skill Development.md
Chapter 6 Summary, Takeaways, and Actions.md
Glossary.md"

IFS="
"
[ -e "$OUT" ] && rm "$OUT"

for F in $FILES
do
    TITLE=$(echo $F | sed 's/.md//')
    echo "# $TITLE" >> "$OUT"
    cat $F | grep -v "^- \[\[#" >> "$OUT"
    echo "" >> "$OUT"
    echo "" >> "$OUT"
    echo "---" >> "$OUT"
done
