#!/bin/bash


if [ $# -eq 1 ]
then
    TEMPLATE="$1"
else
    read -p "which template to remove? " TEMPLATE
fi
[ -z "$TEMPLATE" ] && exit

IFS="
"

MASTER=$HOME/Obsidian/MasterTemplates

for DIR in $(find $HOME/Obsidian -type d -iname 'Templates')
do
    if [ -e "$DIR/$TEMPLATE" ]
    then
        echo "Removing $DIR/$TEMPLATE"
        rm "$DIR/$TEMPLATE"
    fi
done
if [ -e "$MASTER/$TEMPLATE" ] 
then 
    echo "Removing $MASTER/$TEMPLATE"
    rm "$MASTER/$TEMPLATE"
fi

