#!/bin/bash

WORD=$1
if [ $# -eq 0 ]
then
    exit 1
elif [ $# -eq 1 ]
then
    PADLEN=10
elif [ $# -eq 2 ]
then
    PADLEN=$2
fi


LEN=$(echo $WORD | wc -c)
LEN=$(($LEN - 1))
if [ $PADLEN -le $LEN ]
then
   echo $WORD
else
    PADS=$(($PADLEN - $LEN))
    echo -n $WORD
    for S in $(range 1 $PADS)
    do
        echo -n " "
    done
    echo ""
fi
