#!/usr/bin/python3

import sys

from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget, QPushButton, QLabel, QDateTimeEdit, QTabWidget, QTableWidget, QTableWidgetItem, QSpinBox, QCalendarWidget, QTimeEdit, QComboBox, QHBoxLayout
from PyQt5.QtCore import Qt, QDateTime, QDate, QTime
import psycopg2
from configparser import ConfigParser

class DatabaseManager:
    def __init__(self, config_file):
        self.config = self.read_db_config(config_file)
        self.conn = self.connect()

    def read_db_config(self, filename='/etc/rainRecorder/database.ini', section='postgresql'):
        parser = ConfigParser()
        parser.read(filename)
        db = {}

        if parser.has_section(section):
            params = parser.items(section)
            for param in params:
                db[param[0]] = param[1]
        else:
            raise Exception(f'Section {section} not found in the {filename} file')

        return db

    def connect(self):
        conn = None
        try:
            params = self.config
            conn = psycopg2.connect(**params)
            return conn
        except (Exception, psycopg2.DatabaseError) as error:
            print(error)

    def close_connection(self):
        if self.conn is not None:
            self.conn.close()

class RainDataApp(QMainWindow):
    def __init__(self, db_manager):
        super().__init__()
        self.db_manager = db_manager
        self.init_ui()

    def init_ui(self):
        self.central_widget = QTabWidget(self)

        self.input_tab = RainDataInputTab(self.db_manager)
        self.retrieval_tab = RainDataRetrievalTab(self.db_manager)

        self.central_widget.addTab(self.input_tab, "Input")
        self.central_widget.addTab(self.retrieval_tab, "Retrieval")

        self.setCentralWidget(self.central_widget)

        self.setWindowTitle('Rain Data Recorder')
        self.setGeometry(600, 100, 300, 900)
        self.show()

class RainDataInputTab(QWidget):
    def __init__(self, db_manager):
        super().__init__()
        self.db_manager = db_manager
        self.init_ui()

    def init_ui(self):
        self.input_volume = QSpinBox(self)
        self.input_date = QCalendarWidget(self)
        self.input_hour = QComboBox(self)
        self.input_minute = QComboBox(self)

        current_time = QDateTime.currentDateTime().time()
        current_hour = current_time.hour()
        current_minute = current_time.minute()

        for hour in range(24):
            self.input_hour.addItem(str(hour))
        self.input_hour.setCurrentIndex(current_hour)

        for minute in range(60):
            self.input_minute.addItem(str(minute))
        self.input_minute.setCurrentIndex(current_minute)

        submit_button = QPushButton('Submit', self)
        submit_button.clicked.connect(self.submit_data)

        layout = QVBoxLayout(self)
        layout.addWidget(QLabel('Enter Rain Volume:'))
        layout.addWidget(self.input_volume)

        date_time_layout = QHBoxLayout()
        date_time_layout.addWidget(QLabel('Enter Date:'))
        date_time_layout.addWidget(self.input_date)
        date_time_layout.addWidget(QLabel('Enter Time:'))
        date_time_layout.addWidget(self.input_hour)
        date_time_layout.addWidget(self.input_minute)

        layout.addLayout(date_time_layout)
        layout.addWidget(submit_button)

    def submit_data(self):
        volume = self.input_volume.value()
        date = self.input_date.selectedDate().toString(Qt.ISODate)
        hour = self.input_hour.currentText()
        minute = self.input_minute.currentText()

        if volume and date and hour and minute:
            self.save_to_database(f"{date} {hour}:{minute}", volume)
        else:
            print("Volume, Date, Hour, and Minute cannot be empty.")

    def save_to_database(self, date_time, volume):
        try:
            cursor = self.db_manager.conn.cursor()
            cursor.execute("INSERT INTO rain_data (date_time, volume) VALUES (%s, %s)", (date_time, volume))
            self.db_manager.conn.commit()
            print("Record inserted successfully")
        except (Exception, psycopg2.Error) as error:
            print(f"Error inserting data into the database: {error}")
        finally:
            if cursor:
                cursor.close()

class RainDataRetrievalTab(QWidget):
    def __init__(self, db_manager):
        super().__init__()
        self.db_manager = db_manager
        self.init_ui()

    def init_ui(self):
        self.start_date = QCalendarWidget(self)
        self.end_date = QCalendarWidget(self)
        self.start_hour = QComboBox(self)
        self.end_hour = QComboBox(self)
        self.start_minute = QComboBox(self)
        self.end_minute = QComboBox(self)
        self.total_rain_label = QLabel(self)

        current_time = QDateTime.currentDateTime().time()
        current_hour = current_time.hour()
        current_minute = current_time.minute()
        start_default_date = QDate(QDate.currentDate().year(), QDate.currentDate().month(), 1)
        end_default_date = QDate(QDate.currentDate().year(), QDate.currentDate().month(), QDate.currentDate().daysInMonth())

        self.start_date.setSelectedDate(start_default_date)
        self.end_date.setSelectedDate(end_default_date)


        for hour in range(24):
            self.start_hour.addItem(str(hour))
            self.end_hour.addItem(str(hour))
        #-# self.start_hour.setCurrentIndex(current_hour)
        #-# self.end_hour.setCurrentIndex(current_hour)
        self.start_hour.setCurrentIndex(0)
        self.end_hour.setCurrentIndex(23)

        for minute in range(60):
            self.start_minute.addItem(str(minute))
            self.end_minute.addItem(str(minute))
        #-# self.start_minute.setCurrentIndex(current_minute)
        #-# self.end_minute.setCurrentIndex(current_minute)
        self.start_minute.setCurrentIndex(0)
        self.end_minute.setCurrentIndex(59)

        retrieve_button = QPushButton('Retrieve Data', self)
        retrieve_button.clicked.connect(self.retrieve_data)

        self.table = QTableWidget(self)

        layout = QVBoxLayout(self)
        layout.addWidget(QLabel('Enter Start Date:'))
        layout.addWidget(self.start_date)
        layout.addWidget(QLabel('Enter Start Time:'))
        start_time_layout = QHBoxLayout()
        start_time_layout.addWidget(self.start_hour)
        start_time_layout.addWidget(self.start_minute)
        layout.addLayout(start_time_layout)

        layout.addWidget(QLabel('Enter End Date:'))
        layout.addWidget(self.end_date)
        layout.addWidget(QLabel('Enter End Time:'))
        end_time_layout = QHBoxLayout()
        end_time_layout.addWidget(self.end_hour)
        end_time_layout.addWidget(self.end_minute)
        layout.addLayout(end_time_layout)

        layout.addWidget(retrieve_button)
        layout.addWidget(QLabel('Total Rain:'))
        layout.addWidget(self.total_rain_label)
        layout.addWidget(self.table)

    def retrieve_data(self):
        start_date = self.start_date.selectedDate().toString(Qt.ISODate)
        end_date = self.end_date.selectedDate().toString(Qt.ISODate)
        start_hour = self.start_hour.currentText()
        end_hour = self.end_hour.currentText()
        start_minute = self.start_minute.currentText()
        end_minute = self.end_minute.currentText()

        try:
            cursor = self.db_manager.conn.cursor()
            query = f"SELECT * FROM rain_data WHERE date_time BETWEEN '{start_date} {start_hour}:{start_minute}' AND '{end_date} {end_hour}:{end_minute}'"
            cursor.execute(query)
            records = cursor.fetchall()

            total_rain_query = f"SELECT SUM(volume) FROM rain_data WHERE date_time BETWEEN '{start_date} {start_hour}:{start_minute}' AND '{end_date} {end_hour}:{end_minute}'"
            cursor.execute(total_rain_query)
            total_rain = cursor.fetchone()[0]
            total_rain = total_rain if total_rain else 0

            self.display_data(records)
            self.total_rain_label.setText(str(total_rain))
        except (Exception, psycopg2.Error) as error:
            print(f"Error retrieving data from the database: {error}")
        finally:
            if cursor:
                cursor.close()

    def display_data(self, records):
        self.table.clear()
        self.table.setRowCount(len(records))
        self.table.setColumnCount(3)
        self.table.setHorizontalHeaderLabels(["ID", "Date and Time", "Volume"])
        #self.table.horizontalHeader().SetResizeMode(QtWidgets.QHeaderView.Stretch)
        #self.table.horizontalHeader().setSectionResizeMode(QTableWidgetItem.QHeaderView.ResizeToContents)
        #self.table.horizontalHeader().setSectionResizeMode(QTableWidgetItem.QHeaderView.ResizeToContents)

        for row, record in enumerate(records):
            for col, value in enumerate(record):
                item = QTableWidgetItem(str(value))
                self.table.setItem(row, col, item)

def main():
    app = QApplication(sys.argv)
    db_manager = DatabaseManager('/etc/rainRecorder/database.ini')
    main_win = RainDataApp(db_manager)
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()
