#!/bin/bash

OIFS=$IFS
IFS="
"
if [ $# -eq 1 ]
then
    FUNC=$1
else
    FOUND=0
    for LINE in $(tail -30 $0)
    do
        if [[ "$LINE" = *"case"* ]]
        then
            FOUND=1
        elif [[ "$LINE" = *"esac"* ]]
        then
            FOUND=0
            break
        fi
        if [ $FOUND -gt 0 ]
        then
            if [[ $LINE = *")"* ]]
            then
                echo $LINE | sed 's/)//'
            fi
        fi
    done

    read -p "which function would you like? " FUNC
    [ -z $FUNC ] && exit
fi

IFS=$OIFS
#------------------------------------------------------
# Functions
func_new(){
    echo "
#!/bin/bash

# Michael Piko michael@piko.com.au
# Variables
"
}

func_if(){
    echo "
    if []
    then
        echo \"\"
    fi" 
}

func_1arg(){
    echo "
    if [ \$# -eq 1 ]
    then
        ARG=\$1
    else
        read -p \"which function would you like? \" ARG
        [ -z \$ARG ] && exit
    fi" | sed 's/^    //'
}

func_ifelse(){
    echo "
    if []
    then
        echo \"\"
    else
        echo \"\"
    fi"
}


func_elif(){
    echo "
    if []
    then
        echo \"\"
    elif []
        echo \"\"
    else
        echo \"\"
    fi"
}

func_yesno() {
    echo "
    read -p \"Ask something? \(Y/n\)\" RESP
    [ -z "\$RESP" ] && exit
    [ "\$RESP" = 'y' ] && RESP='Y'
    if [ \$RESP = 'Y' ]
    then
        echo \"\"
    fi"
}

func_interactive() {
    echo "
    case \$- in
      *i*) echo \"This shell is interactive\";;
      *) echo \"This is a script\";;
    esac"
}

func_menu() {
    echo "
    PS3=\"Enter a number: \"

    select character in Sheldon Leonard Penny Howard Raj
    do
        echo \"Selected character: \$character\"
        echo \"Selected number: \$REPLY\"
    done"
}

func_executable() {
    echo "
if which \"\$ARG\" > /dev/null
then
    echo \$ARG exists
else
    echo \"\$ARG not found\"
    # exit N
fi
"
}

func_getopts() {
    cat<<EOG
# --------------------------------------------
# Parse options
# --------------------------------------------
while getopts ":m:dqh" opt; do
    case \$opt in
        m) MOD="\$OPTARG" ;;
        d) DEBUG=1 ;;
        q) QUIET=1 ;;
        h) show_help ;;
        \\?) echo "Invalid option: -\$OPTARG" >&2; show_help ;;
        :) echo "Option -\$OPTARG requires an argument." >&2; show_help ;;
    esac
done
EOG
}

func_array_loop() {
    cat<<EOB

FILE=file.csv

readarray -t LINES < <(head \$FILE)

for LINE in "\${LINES[@]}"
do
    echo \$LINE
done
EOB
}

#------------------------------------------------------
# options
case $FUNC in
    new)
        func_new;;
    1arg)
        func_1arg;;
    if)
        func_if;;
    ifelse)
        func_ifelse;;
    elif)
        func_elif;;
    askyesno)
        func_yesno;;
    interactive)
        func_interactive;;
    executable)
        func_executable;;
    getopts)
        func_getopts;;
    array_loop)
        func_array_loop;;
    menu)
        func_menu;;
    *)
        echo "invalid option: $FUNC";;
esac

