#!/bin/bash

echo "Add: michael ALL=(ALL) NOPASSWD:ALL to suders"
read NOW

sudo visudo

sudo apt update
sudo apt upgrade -y
sudo apt autoremove -y
apt install -y vim apcalc
echo "

configure vim as the editor"
read NOW
sudo update-alternatives --config editor

./installGit
./installChrom


