#!/bin/bash

# this script is intended to be run from /data with
# /data/Pi folder with files: 
# chromium-browser_56.0.2924.84-0ubuntu0.14.04.1.1011.deb installGit installChrom
# also a /data/ssh folder



echo "Add: michael ALL=(ALL) NOPASSWD:ALL to suders"
read NOW

sudo visudo

sudo apt update
sudo apt upgrade -y
sudo apt autoremove -y
sudo apt install -y vim apcalc nfs-common
echo "

configure vim as the editor"
read NOW
sudo update-alternatives --config editor

rsync -av ssh ~/.ssh

cd Pi
./installGit
#./installChrom

cd ~

if [ -f bin/bash_aliases ]
then
    cp bin/bash_aliases .bash_aliases
    chmod 755 .bash_aliases
fi
if [ -f bin/vimrc ]
then
    cp bin/vimrc .vimrc
    chmod 644 .vimrc
fi
