#!/bin/bash

cd /etc/openvpn

TUN=$(ifconfig tun0| grep -w inet | awk '{print $1}') 2> /dev/null

if [ -z $TUN ]
then
    sudo openvpn --config /etc/openvpn/client.conf &
    sudo /etc/openvpn/client.up
fi

