#!/bin/bash

REPOS=$HOME/obsidian-git-sync


sleep $(echo $RANDOM | cut -c1)

for DIR in $REPOS
do
    cd $DIR

    GSTATUS=$(git status --porcelain)
    
    if [ ${#GSTATUS} -ne 0 ]
    then
        git add --all
        git commit -m "Automated sync: $GSTATUS"
        git pull --rebase
        git push
    fi
done
