#!/bin/bash

. setEnvironment.sh

buildpath $LOGDIR
recordscriptrun $(basename $0) $LOGBASE

cd

SOURCE=bin/
DEST=bin/
VERBOSE="n"

if [ $# -eq 1 ] && [ $1 = "-v" ]
then
   VERBOSE="y"
fi

if isHostUp ltsp
then
  onScreen $VERBOSE rsync $SOURCE to ltsp
  rsync -a --delete -e ssh $SOURCE ltsp:$DEST
fi
if isHostUp media-laptop
then
  onScreen $VERBOSE rsync $SOURCE to media-laptop
  rsync -a --delete -e ssh $SOURCE media@media-laptop:$DEST
fi
if isHostUp media-laptop
then
  onScreen $VERBOSE rsync $SOURCE to rpi
  rsync -a --delete -e ssh $SOURCE pi@rpi:$DEST
fi
if isHostUp media-laptop
then
  onScreen $VERBOSE rsync $SOURCE to vserver001
  rsync -a --delete -e ssh $SOURCE vserver001:$DEST
fi

