#!/bin/bash

. setEnvironment.sh

buildpath $LOGDIR
recordscriptrun $(basename $0) $LOGBASE

cd

SOURCE=bin/
DEST=bin/
#REMOTE=media@media-laptop


if [ $# -eq 1 ] && [ $1 = "-v" ]
then
   SWITCHES=avPe
else
   SWITCHES=ae
fi


rsync -$SWITCHES --delete ssh $SOURCE ltsp:$DEST
rsync -$SWITCHES --delete ssh $SOURCE media@media-laptop:$DEST
rsync -$SWITCHES --delete ssh $SOURCE pi@pi:$DEST


