#!/bin/bash

LOCKS="/var/lib/apt/lists/lock /var/lib/dpkg/lock"
NOW=$(date +%s)
TOL=3600 # seconds


removelocks() {
for I in $LOCKS
do
  if [ -e $I ]
  then
    #stat --print %y $I
    MOD=$(stat --print %Y $I)
    NUM=$(calc $MOD + $TOL)
    if [ $NUM -lt $NOW ]
    then
      echo Removing stale lock: $I
      sudo rm $I
    else
      : #echo MOD=$MOD NUM=$NUM
    fi
  fi
done
}

removelocks

sudo apt update
sudo apt upgrade -y
sudo apt autoremove -y

echo "updating ~/bin"
cd ~/bin
git pull
echo "updating ~/localbin"
cd ~/localbin
git pull

echo updating .mbashrc
cat $HOME/bin/mbashrc > $HOME/.mbashrc
echo updating .bash_aliases
cat $HOME/bin/bash_aliases > $HOME/.bash_aliases
echo updating .vimrc

if [ -e ~/Projects/setupNewMachine ]
then
    rm -rf ~/Projects/setupNewMachine
fi

removelocks
cat $HOME/bin/vimrc > $HOME/.vimrc
