#!/bin/bash

LOCKS="/var/lib/apt/lists/lock /var/lib/dpkg/lock"
NOW=$(date +%s)
TOL=3600 # seconds


removelocks() {
for I in $LOCKS
do
  if [ -e $I ]
  then
    #stat --print %y $I
    MOD=$(stat --print %Y $I)
    NUM=$(($MOD + $TOL))
    if [ $NUM -lt $NOW ]
    then
      echo Removing stale lock: $I
      sudo rm $I
    else
      : #echo MOD=$MOD NUM=$NUM
    fi
  fi
done
}

removelocks


sudo apt update
sudo apt upgrade -y
sudo apt autoremove -y
if which snap > /dev/null 2>&1
then
    sudo snap refresh
fi

for BIN in bin localbin
do
    if [ -d ~/$BIN ]
    then
        echo "updating ~/$BIN"
        cd ~/$BIN
        git pull
    fi
done

if [ -d ~/bin ]
then
    echo updating .mbashrc
    cat $HOME/bin/mbashrc > $HOME/.mbashrc
    echo updating .bash_aliases
    cat $HOME/bin/bash_aliases > $HOME/.bash_aliases
    echo updating .vimrc
fi

if [ -e ~/Projects/setupNewMachine ]
then
    rm -rf ~/Projects/setupNewMachine
fi

removelocks
cat $HOME/bin/vimrc > $HOME/.vimrc
