#!/bin/bash
#
# https://www.oracle.com/technical-resources/articles/it-infrastructure/admin-manage-vbox-cli.html

SELF=$(basename $0)
DATE=$(date '+%y%m%d_%H%M')

#check() {
#    VMS=$(VBoxManage list vms | cut -f2 -d\")
#    echo $VMS
#}

if [ $# -eq 0 ]
then
    $SELF list
    $SELF abcdef
    exit
fi

checkinlist(){
    #for VM in $(VBoxManage list vms | cut -f2 -d\" | tr '\n' ' ')
    for VM in $(VBoxManage list vms | cut -f2 -d\")
    do
        #if [ "$1" = *"$VM"* ]
        if [ "$@" = "$VM" ]
        then
            return 0
        fi
    done
    return 1
}

case $1 in
    list)
        VBoxManage list vms | cut -f2 -d\";;
    running)
        VBoxManage list runningvms;;
    start)
        if checkinlist $2;
        then
            #VBoxManage snapshot "$2" take $DATE;
            VBoxManage startvm "$2" --type headless;
        else
            echo "$2 not found";
        fi;;
    pause)
         VBoxManage controlvm "$2" pause;;
    resume)
        VBoxManage controlvm "$2" resume;;
    stop)
        VBoxManage controlvm "$2" poweroff;;
    detail)
        VBoxManage list -l runningvms;;
    status)
        VBoxManage list -l runningvms | grep -E "Name:|State:";;
    *)
       #$0 status
        echo $SELF "[list|running|pause vm|resume vm|stop vm|detail|status]"
        echo "give me some options"
esac

