#!/bin/bash


PIDS=$(ps ax | grep vmplayer | grep -v grep | sed 's/^ \+//' | cut -f1 -d" ")
#echo $PIDS


for PID in $PIDS
do
  INSTANCE=$(ps ax | grep $PID | grep -v grep | sed 's/ \+/ /g'|  awk -F" " '{print $NF}')
  #echo INSTANCE = $INSTANCE
  VMHOST=$(echo $INSTANCE | cut -f4 -d"/")
  VMS[$PID]=$VMHOST
  echo "Requesting $VMHOST to shutdown"
  ssh $VMHOST "sudo shutdown -h now" 
done


# wait for vms to shutdown
while [ ! -z "$PIDS" ]
do
  sleep 1
  for PID in $PIDS
  do
    INSTANCE=$(ps ax | grep $PID | grep -v grep | sed 's/ \+/ /g'|  awk -F" " '{print $NF}')
    if [ -z "$INSTANCE" ]
    then
        echo ${VMS[${PID}]} has shut down
        PIDS=$(echo $PIDS | sed "s/$PID//g")
    fi
  done
done


#sudo shutdown -h now


