#!/bin/bash


#[ $(hostname) = "Mate" ] && CONF=/home/michael/vpnkeys/UTE_michael.ovpn
#[ $(hostname) = "max" ] && CONF=/home/michael/vpnkeys/VPN_max.ovpn
#[ $(hostname) = "maxine" ] && CONF=/home/work/vpnkeys/VPN_max.ovpn
#[ $(hostname) = "development" ] && CONF=/root/vpnkeys/vpnDev.ovpn
#[ $(hostname) = "dev" ] && CONF=/root/vpnkeys/ramdev2Ute.ovpn
#[ $(hostname) = "nas" ] && CONF=/home/michael/vpnkeys/UTE_nas.ovpn

CONF=/home/michael/vpnkeys/VPN_${hostname}.ovpn

if [ -f "$CONF" ]
then
    sudo openvpn --config $CONF
else
    echo "No configuration for this machine"
fi
