#!/bin/bash

CONF=/home/michael/vpnkeys/UTE_michael.ovpn

[ $(hostname) = "max" ] && CONF=/home/michael/vpnkeys/UTE_max.ovpn
[ $(hostname) = "development" ] && CONF=/root/vpnkeys/vpnDev.ovpn
[ $(hostname) = "dev" ] && CONF=/root/vpnkeys/ramdev2Ute.ovpn

sudo openvpn --config $CONF
